# Site settings
title: The Sunday Creative
header-img: img/home-bg.png
email: mirandaraymond@me.com
copyright_name: mirandalily
description: > # this means to ignore newlines until "baseurl:"
  a tech blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mirandalily
learn_profile: mirandalily
email_username: mirandaraymond@me.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
